### PR TITLE
Update osbs namespace

### PR DESCRIPTION
**Pull request by gaohoward**
Signed-off-by: Howard Gao <howard.gao@gmail.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by sknot-rh — APPROVED** [review]
https://github.com/jboss-container-images/jboss-amq-6-image/pull/42/files for cp branch

**Comment by gaohoward** [comment]
@goldmann Can you merge this? I'm waiting for it to start rebuilding the cp.
Thanks
Howard

**Comment by goldmann** [comment]
@gaohoward I added you to the team, you have now merge rights.

**Comment by gaohoward** [comment]
@goldmann thanks!

**Pull request merged**
