### PR TITLE
CLOUD-1962: Update AMQ to 6.3 R4

### PR DESCRIPTION
**Pull request by jmtd**
Signed-off-by: Jonathan Dowland <jdowland@redhat.com>

### CODE REVIEW

**Comment by goldmann** [comment]
Are you sure the title of this PR is correct? (and the commit message)

**Comment by jmtd** [comment]
Corrected, thanks!

**Review by goldmann — DISMISSED** [review]
You forgot to update env variables.

**Comment by jmtd** [comment]
> You forgot to update env variables.

Thanks, fixed.

**Review by rwngwn — APPROVED** [review]

**Review by rwngwn — APPROVED** [review]

**Comment by jmtd** [comment]
Force merging it as @dbecvarik has reviewed it but can't merge for some reason (we need to check permissions)

**Pull request merged**
