### PR TITLE
Update amq63 to latest version

### PR DESCRIPTION
**Pull request by gaohoward**
Signed-off-by: Howard Gao <howard.gao@gmail.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by gaohoward** [comment]
@goldmann Hi Marek, I've updated the amq63 version to latest (r8). Please review. Thanks.

**Comment by gaohoward** [comment]
I'm closing this. (could use overrides)

**Comment by goldmann** [comment]
Please note, that after release, you need to sync branches. If you released from dev, then the release and cp branch need to use the same content with the difference, that cp and release branches will have modified references to module repositories to point to a fixed release (`sprint-20` in your case).

**Comment by gaohoward** [comment]
Hi Marek,
I understand that from 1.3 to 1.4 we can see it as a amq63 release. But on the other hand there is sprint-20 which amq63 release refers to. Sprint-20 doesn't look like a formal release name/version. So from cloud team point of view, the 1.3/1.4 upgrade is not a release of a product. Is that correct understanding?
Thanks
Howard

**Comment by goldmann** [comment]
Image development (in many cases) is not related to product development. My comment above was about image development. You need to ensure that source code reflects the correct content that was used to build the image. We ensure this by merging the content of branches and pointing (if necessary), to correct references in modules (`sprint-20` in your case. I have provided you over email links to CE wiki which explain the process.

1.4 was release of image of the product.

**Comment by gaohoward** [comment]
Thanks Marek. So I think this PR is valid one. I'm reopening it for review. 
Also I'll open a PR on the openshift repo to update the 'sprint-20'.

**Comment by goldmann** [comment]
Was the latest image (1.4) built with this patch?

**Comment by gaohoward** [comment]
yes, it's the latest (R8)

**Comment by goldmann** [comment]
In such case it **must be** merged to reflect the correct source.

**Review by goldmann — APPROVED** [review]

**Comment by goldmann** [comment]
After merging this, please prepare two other PR to the other branches to sync content as discussed.

**Comment by gaohoward** [comment]
Thanks Marek. Will do the others after that.

**Pull request merged**
