### PR TITLE
Update version for new image

### PR DESCRIPTION
**Pull request by gaohoward**
Signed-off-by: Howard Gao <howard.gao@gmail.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by gaohoward** [comment]
@stanlyDoge Hi Stan, can you review this? it's for https://issues.jboss.org/browse/PATCH-2631. Thx.

**Review by sknot-rh — CHANGES_REQUESTED** [review]
Please, change URL to https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=59151&product=jboss.amq.broker&version=6.3.0&downloadType=securityPatches

**Comment by gaohoward** [comment]
ah sorry about that. I'll do it.

**Comment by gaohoward** [comment]
@stanlyDoge done.

**Comment by sknot-rh** [comment]
LGTM. I would ask Marek for review as well.

**Review by sknot-rh — APPROVED** [review]

**Review by goldmann — APPROVED** [review]

**Pull request merged**
